name: Code Climate Test Coverage
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - production
      - github-actions-testing
  pull_request:
    branches:
      - production
      - github-actions-testing
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs: 
  test:
    name: steve
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
      with:
        coverageCommand: yarn coverage
      debug: true
    

